package com.revature.driver;

public enum UIState {
	WELCOME, REGISTER, LOGIN, USER_MENU, SUPERUSER_MENU, VIEW_USERS, VIEW_BALANCES,
	CREATE_USER, CREATE_ACCOUNT, UPDATE_USER, DELETE_USER, DELETE_ACCOUNT, CREATE_TRANSACTION, LOGOUT, EXIT
}
